### ISSUE TITLE
Change ACL branding to GWF branding

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/gwf-publications#1]
Top left banner "ACL Anthology" should be rebranded to GWF Anthology. Find assets in the GWF main page: https://gwf.usask.ca/

Also swap out the favicon.

**Comment by mobehbooei** [comment]
Done

**Comment by lintool** [comment]
Can we use the GWF logo as the favicon also?

**Comment by mobehbooei** [comment]
I think we can. I will do so!

**Comment by mobehbooei** [comment]
Done
