### ISSUE TITLE
Inconsistency in author names

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/gwf-publications#15]
+ For some, we just get first initials:
  + https://gwf-uwaterloo.github.io/gwf-publications/G22-43001/ (I think it's because the original article only uses first initials? https://www.nature.com/articles/s41558-022-01428-z)
  + https://gwf-uwaterloo.github.io/gwf-publications/G22-4001/ (same here: https://cdnsciencepub.com/doi/abs/10.1139/cjfr-2021-0183)
+ For some, the middle initials do not have dots: 
  + https://gwf-uwaterloo.github.io/gwf-publications/G22-41001/ (https://iopscience.iop.org/article/10.1088/1748-9326/ac6005)

@mobehbooei I think we're ingesting whatever the publisher exports, based on the "official" version of the published paper?

**Comment by dukaczka** [comment]
Are the inconsistencies reconcilable through a lookup list of variations? Or do the variations result in a fragmented record - 5 pubs by J. Pomeroy, 10 by John Pomeroy for example?

**Comment by mobehbooei** [comment]
You are right @lintool . We are showing what we get from APIs. I will change the names in the next version because I am using another API for getting names (for University widget). After that, all the remaining name variants should handle manually.

**Comment by mobehbooei** [comment]
With the unified version of author names, this problem is almost solved!
