### ISSUE TITLE
Main landing page should list all papers by year, reverse chronologically

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/gwf-publications#2]
Something like the layout of an author profile?

**2022**
+ paper
+ paper
+ paper
+ ...

**2021**
+ paper
+ paper
+ paper
+ ...

**Comment by mobehbooei** [comment]
so the year pages would be deleted, right?

**Comment by mobehbooei** [comment]
Done

**Comment by lintool** [comment]
Great!

The current year headings look like this:

<img width="291" alt="Screen Shot 2022-11-21 at 8 30 35 AM" src="https://user-images.githubusercontent.com/313837/203068002-458f83dd-4a67-40a0-8c59-c94a57174aa4.png">

Can we make them look more like this?

<img width="895" alt="Screen Shot 2022-11-21 at 8 31 17 AM" src="https://user-images.githubusercontent.com/313837/203068083-c2bede88-623d-422b-92b0-953243d11048.png">

And would it be possible to add some sort of widget for year (on the main landing page)?

<img width="311" alt="Screen Shot 2022-11-21 at 8 31 24 AM" src="https://user-images.githubusercontent.com/313837/203068186-d5c84fdf-b6cf-41a0-87a5-953aade65bb8.png">

**Comment by lintool** [comment]
Done!
