### ISSUE TITLE
Download multiple bib entries

### ISSUE THREAD

**Issue by julemai** [gwf-uwaterloo/gwf-publications#22]
I really like the website and its functionality; especially that one can download the BibTeX entries for each publication. I was wondering if it would be possible to select multiple publications and download all their bib entries at once.

**Comment by lintool** [comment]
Hi @julemai - the website is modeled after https://aclanthology.org/ - if you go to the site, on the left, you can download _all_ bibtex entries. Would something like that work for you?

**Comment by julemai** [comment]
Yes, that would be great!!

**Comment by mobehbooei** [comment]
Hello @julemai. I think I can add this to the main page. @lintool, Do you want me to do it?

**Comment by lintool** [comment]
hi @julemai - I'll discuss with @mobehbooei offline about prioritization... Thanks for filing the issue!

**Comment by dukaczka** [comment]
I like this idea too. Would one be able to export the results of a search? For instance if one is looking at a specific author or perhaps if a project tag is added? This would be very useful.

**Comment by mobehbooei** [comment]
The main Idea is done
