### ISSUE TITLE
general esthetics 1

### ISSUE THREAD

**Issue by bhaleka** [gwf-uwaterloo/gwf-publications#4]
- there should not be publications prior to 2016 
- GWF/CFERF Logo should be somewhere on page
- Should change Welcome to the GWF Anthology! to Welcome to Global Water Futures Peer Review Publications!
- filter by  author, `university/institutions` and projects
- Some have abstracts (abs) and some do not, but all these are peer review articles, so all of them should have an abstract
-  the contents in red on the landing page for each year, seems a bit repetitive ( see image below)
![image](https://user-images.githubusercontent.com/7219252/202568697-f33a3b0c-50e5-4234-8808-cd3601b9a1f1.png)

- fonts ( some article titles are upper case, while some are lower case) while place name needs to be capitalize
![image](https://user-images.githubusercontent.com/7219252/202570404-48eac1b3-361f-424e-81d4-1b668f862127.png)

**Comment by mobehbooei** [comment]
Done
