### ISSUE TITLE
Start collapsing multiple research profiles wrt name variants

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/gwf-publications#6]
This is going to take some time to completely get right: name variants need to be collapsed.

E.g., these are the same people:

https://gwf-uwaterloo.github.io/gwf-publications/people/J/John-Pomeroy/
https://gwf-uwaterloo.github.io/gwf-publications/people/J/John-W-Pomeroy/
https://gwf-uwaterloo.github.io/gwf-publications/people/J/J-W-Pomeroy/

And:

https://gwf-uwaterloo.github.io/gwf-publications/people/P/Philippe-Van-Cappellen/
https://gwf-uwaterloo.github.io/gwf-publications/people/P/P-Van-Cappellen/

**Comment by mobehbooei** [comment]
All the author has one representation in this version of website. It is connected to their semantic scholar ID
