### ISSUE TITLE
Fix comma placement

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/gwf-publications#7]
<img width="833" alt="Screen Shot 2022-11-23 at 11 49 07 AM" src="https://user-images.githubusercontent.com/313837/203605234-405fdf16-2c50-4a98-942e-e130319810d2.png">

Should be "Mazda Kompanizare, Richard M. Petrone, Merrin L. Macrae, Kevin De Haan, Myroslava Khomik" -> note, current display has extra spaces before the commas.

**Comment by lintool** [comment]
Hrm... there are still places with pipes `|` instead of commas... https://gwf-uwaterloo.github.io/gwf-publications/events/gwf-2016/#year_2021

**Comment by mobehbooei** [comment]
Done
