### ISSUE TITLE
Comments from Bryan Tolson

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/gwf-publications#9]
Relaying from email, re: https://gwf-uwaterloo.github.io/gwf-publications/people/B/Bryan-A-Tolson/

- the Liu et al 2021 paper is not GWF work (remove)
- the GRIP-GL paper is missing: https://hess.copernicus.org/articles/26/3537/2022/ (add)

**Comment by mobehbooei** [comment]
Done
